CREATE OR REPLACE TRIGGER TR3_EMPLOYEES
BEFORE INSERT OR DELETE OR UPDATE ON EMPLEADOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG_SALARIO VALUES 
        (:NEW.CODIGO,1,:NEW.SALARIO,SYSDATE,USER,'Insercion');
    END IF;
    IF UPDATING THEN
        INSERT INTO LOG_SALARIO VALUES(:OLD.CODIGO,1,:OLD.SALARIO,SYSDATE,USER,'Actualizar');
        INSERT INTO LOG_SALARIO VALUES(:NEW.CODIGO,:OLD.SALARIO,:NEW.SALARIO,SYSDATE,USER,'Actualizar');   
    END IF;
    IF DELETING THEN
        INSERT INTO LOG_SALARIO VALUES
        (:OLD.CODIGO,1,1,SYSDATE,USER,'Eliminar');
    END IF;
END;


SELECT * FROM LOG_SALARIO;
SELECT * FROM EMPLEADOS;
INSERT INTO EMPLEADOS VALUES (1,'prueba1',10000);
UPDATE EMPLEADOS SET SALARIO = 15000 WHERE CODIGO=1;
DELETE FROM EMPLEADOS WHERE CODIGO =1;